-- SQL to create the required tables with uppercase column names

-- Table for ESTACIONES
CREATE TABLE ESTACIONES (
    ID_ESTACION INT AUTO_INCREMENT PRIMARY KEY,
    ID_ADMINISTRADOR INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    LOCALIZACION VARCHAR(255) NOT NULL
);

-- Table for ESTACIONES_DISPOSITIVOS (assuming many-to-many relationship between ESTACIONES and DISPOSITIVOS)
CREATE TABLE ESTACIONES_DISPOSITIVOS (
    ID_ESTACION INT NOT NULL,
    ID_DISPOSITIVO INT NOT NULL,
    PRIMARY KEY (ID_ESTACION, ID_DISPOSITIVO),
    FOREIGN KEY (ID_ESTACION) REFERENCES ESTACIONES(ID_ESTACION)
);

-- Table for ESTACIONES_USUARIOS (assuming many-to-many relationship between ESTACIONES and USUARIOS)
CREATE TABLE ESTACIONES_USUARIOS (
    ID_ESTACION INT NOT NULL,
    ID_USUARIO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ESTACION),
    FOREIGN KEY (ID_ESTACION) REFERENCES ESTACIONES(ID_ESTACION)
);

-- Table for POSIBLES UNIDADES
CREATE TABLE POSIBLES_MAGNITUDES (
    ID_MAGNITUD INT AUTO_INCREMENT PRIMARY KEY,
    MAGNITUD VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    ESCALA VARCHAR(50)
);

-- Table for UNIDADES
CREATE TABLE UNIDADES (
    ID_UNIDAD INT AUTO_INCREMENT PRIMARY KEY,
    ID_MAGNITUD INT NOT NULL,
    ID_ESTACION INT NOT NULL,
    FOREIGN KEY (ID_MAGNITUD) REFERENCES POSIBLES_MAGNITUDES(ID_MAGNITUD),
    FOREIGN KEY (ID_ESTACION) REFERENCES ESTACIONES(ID_ESTACION)
);

-- Table for MEDIDA
CREATE TABLE MEDIDAS (
    ID_MEDIDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_UNIDAD INT NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_UNIDAD) REFERENCES UNIDADES(ID_UNIDAD)
);
