-- SQL to create the required tables with uppercase column names

-- Table for ESTACIONES
CREATE TABLE ESTACIONES (
    ID_ESTACION INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    LOCALIZACION VARCHAR(255) NOT NULL
);

-- Table for ESTACIONES_DISPOSITIVOS (assuming many-to-many relationship between ESTACIONES and DISPOSITIVOS)
CREATE TABLE ESTACIONES_DISPOSITIVOS (
    ID_ESTACION INT NOT NULL,
    ID_DISPOSITIVO INT NOT NULL,
    PRIMARY KEY (ID_ESTACION, ID_DISPOSITIVO),
    FOREIGN KEY (ID_ESTACION) REFERENCES ESTACIONES(ID_ESTACION)
);

-- Table for ESTACIONES_USUARIOS (assuming many-to-many relationship between ESTACIONES and USUARIOS)
CREATE TABLE ESTACIONES_USUARIOS (
    ID_ESTACION INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_ESTACION, ID_USUARIO),
    FOREIGN KEY (ID_ESTACION) REFERENCES ESTACIONES(ID_ESTACION)
);

-- Table for UNIDADES
CREATE TABLE UNIDADES (
    ID_UNIDAD INT AUTO_INCREMENT PRIMARY KEY,
    MAGNITUD VARCHAR(255) NOT NULL,
    ESCALA VARCHAR(10),
    DESCRIPCION VARCHAR(100) NOT NULL
);

-- Table for ESTACIONES_UNIDADES (linking measurement units to stations)
CREATE TABLE ESTACIONES_UNIDADES (
    ID_ESTACION INT NOT NULL,
    ID_UNIDAD INT NOT NULL,
    PRIMARY KEY (ID_ESTACION, ID_UNIDAD),
    FOREIGN KEY (ID_ESTACION) REFERENCES ESTACIONES(ID_ESTACION),
    FOREIGN KEY (ID_UNIDAD) REFERENCES UNIDADES(ID_UNIDAD)
);

-- Table for MEDIDA
CREATE TABLE MEDIDA (
    ID_MEDIDA INT AUTO_INCREMENT PRIMARY KEY,
    ID_UNIDAD INT NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL,
    FECHA_HORA TIMESTAMP NOT NULL,
    FOREIGN KEY (ID_UNIDAD) REFERENCES UNIDADES(ID_UNIDAD)
);
