from api.router.usuario import usuario_bp
from api.router.medida import medida_bp
from api.router.sensor import sensor_bp
from api.router.estacion import estacion_bp
from api.router.dispositivo import dispositivo_bp
from api.router.unidad import unidad_bp
from api.router.magnitud import magnitud_bp
from api.router.auth import auth_bp
from api.router.estaciones_dispositivos import estaciones_dispositivos_bp
from api.router.estaciones_usuarios import estaciones_usuarios_bp